My_string = input('Who are you? ')
print(len(My_string))
print(My_string .upper())
print(My_string .lower())
print(My_string, ' is sounds like somthing big' .replace(' ', ''))
print(My_string[0])
print(My_string[-1])